[ref #44] アカウント登録時に個人情報保持についての同意を得る(被験者)
nishidalab/entry_form pull request #102
Opened 2017-04-05 05:24 UTC by radcats

(修正点)
participants_controller.rb 同意分表示用のアクションを追加
participant.rb validationにcheckboxにチェックが入っているかの判定を追加
_form.html.erb typeがallの場合checkboxと同意分へのリンクを表示するように修正
routes.rb 同意分のページへのパスを追加
participants_controller_test.rb agreement_pathで同意分のページを開けるかのテストを追加
participant_test.rb agreementがfalseの場合をはじけるかのテストを追加
agreement_html.erb 同意分ページのview

2017-04-05 08:17 UTC, okabi reviewed
UI 考えるとスクロールボックスの方が良い気がしますが、
そこは判断お願いしますー

2017-04-05 08:17 UTC, okabi commented on config/routes.rb
> +
個別にページ作るまでもない(スクロールボックスとかに表示するで良い)気がします。

2017-04-05 08:17 UTC, okabi commented on test/models/participant_test.rb
> +  end
ちゃんとテスト書けてて Good！ 😄

2017-04-07 23:39 UTC, yegawa requested changes
ファイル読み込むところはちょっと分からんけど、それ以外のところは修正したほうが良い気がします。
form_xxxx_tagの実装はコード行数が多くて少し重くなってしまうかもしれないです、ごめんなさい…

2017-04-07 23:39 UTC, yegawa commented on db/migrate/20170407142910_add_agreetext_to_participants.rb
> +    add_column :participants, :agreetext, :string
ただの垢登録の同意文だから一意で良いと思うし
Participantモデルにagreetextを含める必要はないと思います。

2017-04-07 23:39 UTC, yegawa commented on app/views/participants/_form.html.erb
> +    <%= form_text_area f, :agreetext, '個人情報の取り扱い' %>
`text_area_tag` を使えば対象のモデルがなくてもテキストエリアを設置できます。
レイアウトを自動でやるには `app/helpers/application_helper.rb` に `form_xxxx` に似せた感じで
`form_xxxx_tag` を書いてやる必要が出てきます。
`form_xxxx_tag` については用途を考えると `value:` （デフォ値）を指定できるようにすると良いと思います。

2017-04-07 23:39 UTC, yegawa commented on app/views/participants/_form.html.erb
> +    <% participant.agreetext = File.open("#{Rails.root}/app/views/participants/_agreement.html.erb","rb").read.force_encoding("UTF-8") %>
ここちょっと審議。
個人的にはviewで仰々しく読み込むことに違和感がある。
ここで同じようなことやってるけど、まあこっちもコントローラで無理やり取ってきてるし変っちゃ変かも…。
http://stackoverflow.com/questions/35639091/how-do-i-render-a-partial-in-a-text-area-in-a-rails-form

2017-04-15 07:37 UTC, okabi approved these changes
同意文の最初の改行を消してもらったらマージしても良さそう。
ただ、少し気になる点もあります。

- 使用されていない `xx_tag` が量産されている
- `File.open` のところが少し仰々しい気もするけど、代替案も出せないので難しいですね…。

2017-04-15 07:37 UTC, okabi commented on app/views/participants/_agreement.html.erb
> +
スクロールボックスの表示的に最初に改行が入ってると微妙なので、消しといて欲しいです。

2017-04-15 11:53 UTC, okabi approved these changes
良さそう 👍

2017-04-15 12:03 UTC, merged