Issue 46 temp
nishidalab/entry_form pull request #110
Opened 2017-04-21 05:29 UTC by silver-1347

要求を満たすようなテストを自分なりに書いて、そのテストを通るような実装をしたのですが、実際にブラウザでチェックすると、テストでは出ないエラーなどが発生しています。

テストに不足があると思うのでそこのレビューだけでもお願いしたいです。

2017-04-24 05:49 UTC, okabi requested changes
テストは良いと思います 😄 
ざっと動作確認しましたが、レビューした点を直すと想定通りの動作をしてそうです。
コードについてはまだ読み込んでないので、またレビュー依頼もらったときにやります。

2017-04-24 05:49 UTC, okabi commented on app/views/participants/_form.html.erb
>      <%= form_email_field f, :email, 'メールアドレス', description: 'ログインや連絡に用いるため、普段お使いのメールアドレスをご入力ください。' %>
ここの `name` が `:email` になっているため、email_update 時にコントローラがパラメータを受け取れていないようです。
all (アカウント登録)のときは `:email` 、email_update のときは `:new__email` にすると良さそうです。
ただ、その場合現在設定されているメールアドレスがフォームの既存値にならずユーザーに不親切な感じなので、
ケアしてもらえるとありがたいです。

2017-04-24 08:29 UTC, silver-1347 commented
ブラウザでも動くようにできました。レビューお願いします。

バリデーション周りが自信がないです。
+ `email` と`new_email` で相互に被りがないかチェックするようにしたのですがだいぶ怪しい実装になっています。 `particilant.validate_email_uniqueness` と `particilant.validate_email_uniqueness` です。
+ メール更新のフラグとして `changing_email` を用意して `new_email` のバリデーションをするかどうかを決めていますが、これによってバリデーションに漏れが出たりしていないか少し自信がないです。(一応テスト通ってるので大丈夫かとは思っていますが…)

結構いろんなファイルを変更したので大変かと思いますが、よろしくお願いします。

2017-04-27 01:32 UTC, yegawa requested changes
ボヤキとかも多いですが一応レビューしました。
コード上でしか見ていないのであしからず…。

必須
・ `@participant.update_attributes = { :changing_email = false, ...}` にする必要があるかチェック
・ `participant.email_update_authenticated?(token) && !participant.email_update_token_expired?` をまとめる
・ モデルの検索でor使ってるのを書き換える

で後は適当に判断してください

2017-04-27 01:32 UTC, yegawa commented on app/controllers/participants_controller.rb
> +      participant_params = params.require(:participant).permit(:new_email)
好みの問題なんだろうけど、この辺の `params.require(:participant).permit(:hoge)` たちが
1行すごい長くなってくるのが伺えるし情報多いから 
`password_params` とか `email_update_params` `profile_params` とかそんな感じで
別メソッドにまとめてやるのもアリだと思う。

2017-04-27 01:32 UTC, yegawa commented on app/controllers/participants_controller.rb
> +        @participant.email_update_digest = nil
これで更新できたっけ？
`@participant.update_attributes = { :changing_email = false, ...}`
って感じにしないと行けない気がする。
ここに来るときはおそらくバリデーションで弾かれたときだから、このupdate_arrtibutesは成功するはず
（さらにエラーチェックして500に飛ばすとかいうのを書く必要はさすがに無いと思いたい）

2017-04-27 01:32 UTC, yegawa commented on app/controllers/participants_email_update_controller.rb
> +      participant.update(email: new_email,new_email: nil,changing_email: false)
他との統一感がないのと読みにくいので 
`participant.update(email: new_email, new_email: nil, changing_email: false)`
としたいけど、一行が長くなるのは避けたい、
かと言って改行入れるのも変。
こういうときどうすりゃいいんやろうね。

2017-04-27 01:32 UTC, yegawa commented on app/controllers/participants_email_update_controller.rb
> +    end
このメソッド化 好き

2017-04-27 01:32 UTC, yegawa commented on app/controllers/participants_email_update_controller.rb
> +    if participant.email_update_authenticated?(token) && !participant.email_update_token_expired?
この2つの条件ひっくるめたメソッドを
`app/models/concerns/account.rb` あたりに作ったほうがmemberに実装する時ミスらなさそう。

2017-04-27 01:32 UTC, yegawa commented on app/mailers/participant_mailer.rb
> +  end
（この辺もそのうち `concerns` にまとめる作業しないとなあ…）

2017-04-27 01:32 UTC, yegawa commented on app/models/participant.rb
> +    participant = Participant.find_by("deactivated == ? and (email == ? or (changing_email == ? and new_email == ?))",false,email.downcase,true,email.downcase)
Rails 5からSQLべた書きせずにorも書けるようになったらしい！
http://qiita.com/QUANON/items/0033a5adb76d0cb963cd

俺も書いたこと無いから書き方分からんけど、
適当に書きながらrails sのログで実行されてるSQL文と比較して書くと良いと思うよ！

2017-04-27 01:32 UTC, yegawa commented on app/models/participant.rb
> +      participant = Participant.find_by("deactivated == ? and (email == ? or (changing_email == ? and new_email ==   ?))",false,new_email.downcase,true,new_email.downcase)
orに関して、同上。

2017-04-27 01:32 UTC, yegawa commented on app/models/participant.rb
> +    if !new_email.nil?
これ `if new_email` でイケルと思う。

2017-04-27 01:32 UTC, yegawa commented on app/models/participant.rb
> +  end
良い拡張。
将来concernsに行くかも。

2017-04-27 01:32 UTC, yegawa commented on test/integration/participants_settings_test.rb
> +    participant.update(set_email_update_at: participant.set_email_update_at - 86401)
`24.hours.ago(participant.set_email_update_at).ago(1)` 
とか
`24.hours.ago(1.secondes.ago(participant.set_email_update_at)` 
にするか迷いどころ（ago二回はキモいもんなあ…）

2017-04-27 01:32 UTC, yegawa commented on test/integration/participants_settings_test.rb
> +    participant.update(set_email_update_at: participant.set_email_update_at + 86401)
ago使うならsince

2017-04-27 05:28 UTC, okabi requested changes
ざっくりとレビューしました。
セキュリティ的にまずいところがあったので、そこは必須修正でお願いしたいです。

2017-04-27 05:28 UTC, okabi commented on app/controllers/participants_email_update_controller.rb
> +    new_email = params[:e]
`new_email = params[:e].downcase` にしときたい

2017-04-27 05:28 UTC, okabi commented on app/models/participant.rb
> +    if !new_email.nil?
`return if new_email.nil?` としてインデントが深くならないようにしたいかな。

2017-04-27 05:28 UTC, okabi commented on test/mailers/participant_mailer_test.rb
> +    # participant.changing_email = true
特に意図がないならコメントアウトしたものは消しといて欲しいです。

2017-04-27 05:28 UTC, okabi commented on app/models/participant.rb
>    def validate_email_uniqueness
なるほど、メールアドレス更新時に新規登録が来た場合対策か！
よく気付いてくれたと思います。素晴らしい。

2017-04-27 05:28 UTC, okabi commented on app/models/participant.rb
> +  end
メソッド名がちょっと危ない気がします( `new_email` だけで絞ってるように見える)。
アクティブ被験者のみを取っていることをメソッド名から推定できるようにしたい。

2017-04-27 05:28 UTC, okabi commented on db/migrate/20170408160354_add_email_updates_to_participants.rb
> +    add_column :participants, :email_update_token, :string
トークンをDBに保存するのは危ない！！
保存するのは digest のみ。
ちょっと抽象度高くなってて見づらいけど、participant_password_resets_controller.rb とか見て欲しい。

2017-04-27 05:28 UTC, okabi commented on db/migrate/20170408160354_add_email_updates_to_participants.rb
> +    add_column :participants, :changing_email, :boolean, default: false
`changing_email` ってDBに保存しておく必要あるのかな？
`set_email_update_at` だけで判定できる気がします。

2017-04-28 03:49 UTC, silver-1347 commented
レビューいただいた部分について必須事項の全てと、指摘点のいくつかを修正しました。

2017-04-28 04:03 UTC, yegawa requested changes

2017-04-28 04:03 UTC, yegawa commented on app/models/participant.rb
> +    return new_email.nil?
この書き方だと下の方到達しない気がするんだけどどうでしょうか？
return hoge if fuga
なら行けると思うけど
return false if new_email.nil?
とかかね？

2017-04-28 04:29 UTC, silver-1347 commented on app/models/participant.rb
> +    return new_email.nil?
あ…なんか色々頭回ってなかったみたいです…

2017-04-28 04:37 UTC, yegawa approved these changes

2017-04-28 06:39 UTC, okabi reviewed
あとで動作確認しようかと思うけど、とりあえずコードだけ見てぼやきみたいなレビュー。

2017-04-28 06:39 UTC, okabi commented on app/models/participant.rb
>      participant = Participant.find_by(deactivated: false, email: email.downcase)
`Participant.find_active_by_email` を定義して使いたい。
`validate_new_email_uniqueness` の中身も同様。
(できれば他に同様の処理をしている部分を、新しく定義した関数で置き換えてもらえると助かります)

2017-04-28 06:39 UTC, okabi commented on app/models/participant.rb
> +    participant = Participant.find_by(deactivated: false, new_email: email.downcase)
せっかく定義したし、 `Participant.find_active_by_new_email` を使いたい。
`validate_new_email_uniqueness` の中身も同様。
(できれば他に同様の処理をしている部分を、新しく定義した関数で置き換えてもらえると助かります)

2017-04-28 08:53 UTC, okabi reviewed
動作確認しました。さっき見逃してた点もレビューしました。。

2017-04-28 08:53 UTC, okabi commented on app/models/participant.rb
> +    if participant && (id.nil? || participant.id != id) && participant.email_update_token_expired?
ごめん、さっき見逃してたんだけど `participant.email_update_token_expired?` って条件として合ってますか？
更新予定のアドレスと被ってほしくないので、 `!participant.email_update_token_expired?` のような気がします。
( `validate_new_email_uniqueness` の中身も同様)

2017-04-28 08:53 UTC, okabi commented on app/models/participant.rb
> +    if participant && (id.nil? || participant.id != id)
動作確認しました。
動作的には一点だけ修正してほしい点があって、現在設定しているメールアドレスと同じアドレスで更新しようとした時に
バリデーションで弾いてほしいです(それに関するテストもほしいかな)。
おそらく `if participant` で良いかな？

2017-04-28 08:53 UTC, okabi commented on app/models/participant.rb
> +      errors.add(:email, "は既に登録済みです")
ごめん、見逃してたけどこの辺 `:email` から `:new_email` にしないと行けないような気がする。

2017-05-02 04:57 UTC, okabi approved these changes
良さそう 👍

2017-05-02 05:03 UTC, merged