Issue 106
nishidalab/entry_form pull request #118
Opened 2017-05-29 03:33 UTC by silver-1347

機能上は問題無いように実装できたと思います。

サーバー負荷はあまり考えず、コードの読みやすさを優先してAjaxを使って実装しました。
チェックボックス用のヘルパーも作りはしたのですが、見た目がいまいちなのでそこは自信がないです。

レビューお願いします。

2017-05-29 06:33 UTC, okabi requested changes
動作確認して気になったところだけコメントしました。

2017-05-29 06:33 UTC, okabi commented on app/controllers/experiments_controller.rb
> +  def place_checkbox
若干クソリプっぽいのですが、
別窓でログアウトした状態で実施場所を変更すると変なことになります。

2017-05-30 03:19 UTC, silver-1347 commented on app/controllers/experiments_controller.rb
> +  def place_checkbox
変な挙動を修正しました。
ただ実現方法が怪しい気がしています。
javascriptでログインしているかを判別して分岐できればよかったのですが、やり方がわからずこの方法に落ち着いたという感じです。

2017-05-30 05:53 UTC, okabi approved these changes

2017-05-30 05:58 UTC, merged